tinyMCE.addI18n('es.advanced', {
  style_select: "Estilos",
  font_size: "Tamaño",
  fontdefault: "Fuente",
  block: "Formato",
  paragraph: "Párrafo",
  div: "Div",
  address: "Dirección",
  pre: "Preformateado",
  h1: "Encabezado 1",
  h2: "Encabezado 2",
  h3: "Encabezado 3",
  h4: "Encabezado 4",
  h5: "Encabezado 5",
  h6: "Encabezado 6",
  blockquote: "Cita",
  code: "Código",
  samp: "Código de muestra",
  dt: "Término de definición",
  dd: "Descripción de definición",
  span: "Span",
  section: "Section",
  article: "Article",
  hgroup: "HGroup",
  aside: "Aside",
  figure: "Figure",
  bold_desc: "Negrita (Ctrl+B)",
  italic_desc: "Cursiva (Ctrl+I)",
  underline_desc: "Subrayado (Ctrl+U)",
  striketrough_desc: "Tachado",
  justifyleft_desc: "Alinear izquierda",
  justifycenter_desc: "Centrar",
  justifyright_desc: "Alinear derecha",
  justifyfull_desc: "Justificar",
  bullist_desc: "Lista desordenada",
  numlist_desc: "Lista ordenada",
  outdent_desc: "Reducir sangría",
  indent_desc: "Aumentar sangría",
  undo_desc: "Deshacer (Ctrl+Z)",
  redo_desc: "Rehacer (Ctrl+Y)",
  link_desc: "Insertar/editar enlace",
  unlink_desc: "Quitar enlace",
  image_desc: "Insertar/editar imagen avanzado",
  cleanup_desc: "Limpiar código",
  code_desc: "Editar código HTML",
  sub_desc: "Subíndice",
  sup_desc: "Superíndice",
  hr_desc: "Insertar línea horizontal",
  removeformat_desc: "Quitar formato",
  custom1_desc: "Su descripción personalizada aquí",
  forecolor_desc: "Elegir color del texto",
  backcolor_desc: "Elegir color de fondo",
  charmap_desc: "Mapa de caracteres",
  visualaid_desc: "Líneas guía/Elementos invisibles",
  cut_desc: "Cortar",
  copy_desc: "Copiar",
  paste_desc: "Pegar",
  image_props_desc: "Propiedades de imagen",
  newdocument_desc: "Nuevo documento",
  help_desc: "Ayuda",
  blockquote_desc: "Cita",
  clipboard_msg: "Copiar/Cortar/Pegar no está disponible en Mozilla y Firefox.\r\n¿Desea más información sobre estos inconvenientes?",
  path: "Ruta",
  newdocument: "¿Está seguro de que desea borrar todos los contenidos?",
  toolbar_focus: "Ir a botones de herramientas (Alt+Q) - Ir al editor Alt+Z - Ir a la ruta del elemento Alt+X",
  more_colors: "Mas colores",  

    // Accessibility Strings
  shortcuts_desc: 'Ayuda Accesibilidad',
  help_shortcut: '. Pulsa ALT F10 para la barra de herramientas. Pulsa ALT 0 para la ayuda.',
  rich_text_area: "Area de Texto Enriquecido",
  toolbar: "Barra de Herramientas"
});