((function(){window.matchMedia=window.matchMedia||window.msMatchMedia||(function(l,k){var n,i=l.documentElement,h=i.firstElementChild||i.firstChild,m=l.createElement("body"),j=l.createElement("div");
j.id="mq-test-1";j.style.cssText="position:absolute;top:-100em";m.style.background="none";m.appendChild(j);return function(a){j.innerHTML='&shy;<style media="'+a+'"> #mq-test-1 { width: 42px; }</style>';
i.insertBefore(m,h);n=j.offsetWidth==42;i.removeChild(m);return{matches:n,media:a,addListener:function(b){if(!Browser.ie9&&!window.opera){return"";}if(window.retrieve("rokmediaqueries:listener:"+a.replace(/[a-z]|[(|)|:|\s|-]/gi,""),false)){return;
}window.store("rokmediaqueries:listener:"+a.replace(/[a-z]|[(|)|:|\s|-]/gi,""),true);window[window.addListener?"addListener":"attachEvent"]("resize",function(){var d={},e=0,f,c=false;
a.replace(/(\w+-?\w+)\s?:\s?(\d+){1,}/g,function(w,g,u,v,t,x){d[g]=u;e++;});if(!e){return;}else{if(e==1){f=window.getSize();c=false;Object.each(d,function(p,g){if(g=="min-width"){c+=f.x>=p;
}else{if(g=="max-width"){c+=f.x<=p;}else{if(g=="width"){c+=f.x==p;}}}});}else{if(e>1){f=window.getSize();c=true;Object.each(d,function(p,g){if(g=="min-width"){c*=f.x>=p;
}else{if(g=="max-width"){c*=f.x<=p;}else{if(g=="width"){c*=f.x==p;}}}});}}}if(c){return b.call(b,a);}});}};};})(document);})());((function(f,d){if(typeof RokMediaQueries!="undefined"){return;
}var e=new Class({Implements:[Events,Options],options:{queries:["(min-width: 1200px)","(min-width: 960px) and (max-width: 1199px)","(min-width: 768px) and (max-width: 959px)","(min-width: 481px) and (max-width: 767px)","(max-width: 480px)"]},initialize:function(c){this.setOptions(c);
this.queries=this.options.queries;this.queriesEvents={};this.timers=[];for(var b=this.queries.length-1;b>=0;b--){var a=f.matchMedia(this.queries[b]);a.addListener(this._fireEvent.bind(this,this.queries[b]));
this.queriesEvents[this.queries[b]]=[];}},on:function(a,c){if(a=="every"){for(var b=this.queries.length-1;b>=0;b--){this._addOnMatch(this.queries[b],c);
}}else{this._addOnMatch(a,c);}},add:function(b){if(!this.queries.contains(b)){var a;this.queries.push(b);a=f.matchMedia(b);a.addListener(this._fireEvent.bind(this,b));
}if(!this.queriesEvents[b]){this.queriesEvents[b]=[];}},getQuery:function(){var a="";for(var b=this.queries.length-1;b>=0;b--){if(f.matchMedia(this.queries[b]).matches){a=this.queries[b];
break;}}return a;},_fireEvent:function(a){if(!f.matchMedia(a).matches||!Object.getLength(this.queriesEvents)||!this.queriesEvents[a]){return;}for(var b=this.queriesEvents[a].length-1;
b>=0;b--){this.queriesEvents[a][b].delay(5,this,a);}},_addOnMatch:function(a,b){this.add(a);this.queriesEvents[a].push(b);}});f.RokMediaQueries=new e();
})(window,document));